import { readFileSync, writeFileSync } from "fs";

const overridesPath = new URL("../src/data/trackerOverrides.json", import.meta.url);
const researchPath = new URL("../src/data/publicResearchEmails.json", import.meta.url);

const overrides = JSON.parse(readFileSync(overridesPath, "utf-8"));
const research = JSON.parse(readFileSync(researchPath, "utf-8"));

const maxId = overrides.reduce((m, c) => Math.max(m, c.id || 0), 0);

function norm(s) {
  return (s || "").toLowerCase().replace(/[^a-z0-9]/g, "").trim();
}

// Build lookup of existing tracker companies by normalized name
const existingNorms = new Set(overrides.map((c) => norm(c.companyName)));

// Build lookup of research entries
const researchMap = {};
for (const r of research) {
  researchMap[norm(r.companyName)] = r;
}

// New companies from AmbitionBox list (numbered 1-260 with inline emails)
const ambitionCompanies = [
  { name: "Flyweis Technology", emails: ["info@flyweis.technology", "support@flyweis.technology"] },
  { name: "Trangile Services", emails: ["hr@trangile.com", "marketing@trangile.com"] },
  { name: "SmartConnect Technologies", emails: ["transform@smartconnectt.com"] },
  { name: "Bijlipay", emails: ["sales@bijlipay.co.in", "service@bijlipay.co.in"] },
  { name: "Claritus Management Consulting", emails: ["hr@claritusconsulting.com", "info@claritusconsulting.com", "marketing@claritusconsulting.com"] },
  { name: "Mawai Infotech", emails: ["info@mawaimail.com", "sales@mawaimail.com", "marketing@mawaimail.com"] },
  { name: "Absolutelabs", emails: ["contact@absolutelabs.co"] },
  { name: "Quadrafort Technologies", emails: ["info@quadrafort.com"] },
  { name: "ProProfs", emails: ["support@proprofs.com", "sales@proprofs.com", "adsales@proprofs.com", "partners@proprofs.com", "affiliate@proprofs.com"] },
  { name: "NASSCOM", emails: ["hr@nasscom.in"] },
  { name: "The Web Plant", emails: ["sales@thewebplant.com"] },
  { name: "Mobikasa", emails: ["info@mobikasa.com"] },
  { name: "Net Business Solutions", emails: ["connect@netbsolutions.in"] },
  { name: "Creative Info-link", emails: ["info@creativegroup.net.in"] },
  { name: "Quadlabs Technologies", emails: ["info@quadlabs.com", "sales@quadlabs.com"] },
  { name: "Total IT Global", emails: ["contactus@totalitglobal.com"] },
  { name: "Oxigen Services", emails: ["care@oxigenwallet.com", "Company.Secretary@myoxigen.com"] },
  { name: "NovelVox Softwares", emails: ["marketing@novelvox.com"] },
  { name: "Hemmersbach", emails: ["Catherine.Ho@hemmersbach.com"] },
  { name: "JOY IT Solutions", emails: ["sales@joyitsolutions.co"] },
  { name: "Crestech Software", emails: ["apply@crestechsoftware.com", "connect@crestechsoftware.com", "hi@crestechsoftware.com"] },
  { name: "VertexPlus Technologies", emails: ["info@vertexplus.com"] },
  { name: "Intello Labs", emails: ["contact@intellolabs.com"] },
  { name: "HIC Global Solutions", emails: [] },
  { name: "C1 India", emails: ["careers@c1india.com", "enquiry@c1india.com"] },
  { name: "Infotel", emails: ["careers@infotelgroup.in", "info@infotelgroup.in"] },
  { name: "K7 Computing", emails: ["support@k7computing.com"] },
  { name: "Dhanush InfoTech", emails: ["careers@dhanushinfotech.com", "info@dhanushinfotech.com"] },
  { name: "iBoss Tech Solutions", emails: ["hr@ibosstechsolutions.com"] },
  { name: "CS Infocomm", emails: ["info@csinfocomm.com", "support@csinfocomm.com"] },
  { name: "Apptad Technologies", emails: ["Mahima.rastogi@apptadinc.com", "info@apptadinc.com"] },
  { name: "Finoit Technologies", emails: [] },
  { name: "SymphonyAI", emails: [] },
  { name: "Xicom Technologies", emails: ["la@xicom.biz"] },
  { name: "Alethe Consulting", emails: ["sales@aletheconsulting.com"] },
  { name: "Aayan Infotech", emails: ["hr@aayaninfotech.com", "info@aayaninfotech.com"] },
  { name: "Zazz IT Solutions", emails: ["careers@zazz.io", "marketing@zazz.io", "sales@zazz.io"] },
  { name: "PruTech Solutions", emails: ["sales@prutech.com"] },
  { name: "Affixious", emails: ["hr@affixious.com", "info@affixious.com"] },
  { name: "OTS Solutions", emails: ["info@otssolutions.com"] },
  { name: "Stesalit", emails: ["info@stesalitsystems.com", "support@stesalitsystems.com"] },
  { name: "Trident Information Systems", emails: ["info@tridentinfo.com"] },
  { name: "Codleo Consulting", emails: ["consult@codleo.com", "sales@codleo.com"] },
  { name: "Infinite Computing Systems", emails: ["careers@infinite-usa.com"] },
  { name: "Champ Info Software", emails: ["hr_noida@champinfosoft.com"] },
  { name: "Hotfoot Technology Solutions", emails: ["hello@hotfoot.co.in"] },
  { name: "Infoneo Technologies", emails: ["hr@infoneotech.com", "careers@infoneotech.com", "info@infoneotech.com"] },
  { name: "Quaere e-Technologies", emails: ["hr@quaeretech.com", "shiv@quaeretech.com", "sales@quaeretech.com"] },
  { name: "Evolutyz IT Services", emails: ["info@evolutyz.com"] },
  { name: "Elcom Digital", emails: ["info@elcom.digital"] },
  { name: "Analec Infotech", emails: ["hr@analec.com", "support@analec.com", "sales@analec.com"] },
  { name: "Tachyon Technologies", emails: ["info@tachyontech.com"] },
  { name: "Svam International", emails: ["sales@svam.com"] },
  { name: "VAYUZ Technologies", emails: ["careers@vayuz.com", "hello@vayuz.com"] },
  { name: "Crayon Software Experts India", emails: ["marketing.in@crayon.com"] },
  { name: "Tek Ninjas", emails: ["info@tekninjas.com"] },
  { name: "PageTraffic Web-Tech", emails: ["sales@pagetraffic.com"] },
  { name: "Velocity", emails: ["hello@velocity.in"] },
  { name: "Esskay / Esskay Compuservices", emails: ["hr@esskay.in", "contactus@esskay.in", "contact@esskay.in"] },
  { name: "Unicode Systems Pvt Ltd", emails: ["ceo@unicodesystems.in", "amit@unicodesystems.in"] },
  { name: "Brain Technosys", emails: ["info@braintechnosys.com"] },
  { name: "Hummingbird Web Solutions", emails: ["careers@hbwsl.com", "info@hbwsl.com"] },
  { name: "Goodera", emails: ["careers@goodera.com", "info@goodera.com", "partnerships@goodera.com"] },
  { name: "VizExperts", emails: ["hrd@vizexperts.com", "jobs@vizexperts.com"] },
  { name: "Blackcoffer", emails: ["careers@blackcoffer.com", "hello@blackcoffer.com"] },
  { name: "Pranathi Software Services", emails: ["careers@pranathiss.com", "info@pranathiss.com"] },
  { name: "Big Oh Notation / BigOhTech", emails: ["careers@bigohtech.com", "sales@bigohtech.com"] },
  { name: "Nexus Business Solutions", emails: ["sales@nexus-business.com"] },
  { name: "Naviga", emails: ["HR@navigaglobal.com"] },
  { name: "SDLC Corp", emails: ["sales@sdlccorp.com", "info@sdlccorp.com"] },
  { name: "DBA Lounge", emails: ["careers@dbalounge.com", "hr@dbalounge.com", "sales@dbalounge.com"] },
  { name: "FictiveBox Digital", emails: ["tushar@fictivebox.com"] },
  { name: "Transworld Terminals", emails: ["careers@transworld-terminals.com", "connect@transworld-terminals.com", "info@transworld-terminals.com"] },
  { name: "Softpro India Computer Technologies", emails: ["hr@softproindia.in", "info@softproindia.in"] },
  { name: "Digital India Corporation", emails: ["webmaster@digitalindia.gov.in"] },
  { name: "Codvo", emails: ["jobs@codvo.ai", "manasi.rane@codvo.ai"] },
  { name: "Makunai Global Technologies", emails: [] },
  { name: "PolicyX.com", emails: ["hr@policyx.com"] },
  { name: "Jodo", emails: ["whatsup@jodopay.com", "support@jodopay.com"] },
  { name: "Monotype", emails: [] },
  { name: "Alpha Net Consulting", emails: [] },
  { name: "Gapbridge Software Services", emails: [] },
  { name: "DigiLantern", emails: ["info@digilantern.com", "hr@digilantern.co.in"] },
  { name: "SPARX IT Solutions", emails: ["talent@sparxit.com"] },
  { name: "Infrabeat Technologies", emails: ["talent@infrabeat.com"] },
  { name: "Sinclus Engineering Consulting", emails: ["sinclus@sinclus.com"] },
  { name: "Marquis Technologies", emails: ["hr@marquistech.com", "sales@marquistech.com"] },
  { name: "Vertex Global Services", emails: ["info@vertexglobalservices.com"] },
  { name: "Gigmo Solutions", emails: [] },
  { name: "Secure Network Solutions", emails: ["jobs@snsin.com"] },
  { name: "Openview Technologies", emails: ["info@ovtlindia.com"] },
  { name: "I.T. Solutions India Pvt Ltd", emails: ["hrd@itsipl.com"] },
  { name: "Inspace Technologies", emails: ["info@inspacetech.com"] },
  { name: "Tranistics Data Technologies", emails: ["info@tranistics.com"] },
  { name: "Nethues Technologies", emails: ["jobs@hr.nethues.com", "info@nethues.com"] },
  { name: "Caspex Corp", emails: ["info@caspex.com"] },
  { name: "GoKwik", emails: ["merchantcare@gokwik.co", "support@gokwik.co"] },
  { name: "Truspeq Consulting", emails: ["career@truspeq.com"] },
  { name: "Unisoft Global Services", emails: ["pranathi.badekar@unisoftglobalservices.com"] },
  { name: "Kloudrac Softwares", emails: ["hr@kloudrac.com"] },
  { name: "WebBee Global", emails: ["info@webbeeglobal.com"] },
  { name: "StockHolding DMS", emails: ["marketing@stockholdingdms.com"] },
  { name: "Infozech Software", emails: ["sales@infozech.com"] },
  { name: "Tech Superior Consulting", emails: ["careers@techsuperiors.com", "marketing@techsuperiors.com"] },
  { name: "Manras Technologies", emails: ["team@manras.com"] },
  { name: "smartShift Technologies", emails: ["connect@smartShift.com"] },
  { name: "NetCarrots.com", emails: ["career@netcarrotsloyalty.com"] },
  { name: "RipenApps Technologies", emails: ["hr@ripenapps.com", "sales@ripenapps.com", "info@ripenapps.com"] },
  { name: "SabPaisa", emails: ["support@sabpaisa.in"] },
  { name: "Cogniscient Business Solutions", emails: ["hr@cogniscient.in", "sales@cogniscient.in"] },
  { name: "Xotiv Technologies", emails: ["careers@xotiv.com", "talent@xotiv.com", "sales@xotiv.com"] },
  { name: "NetCreativeMind Solutions", emails: ["hr@netcreativemind.com", "info@netcreativemind.com"] },
  { name: "Omnie Solutions", emails: ["hr@omniesolutions.com"] },
  { name: "Zolve", emails: ["hello@zolve.com"] },
  { name: "Zentek Infosoft", emails: ["info@zentekinfosoft.com"] },
  { name: "AtliQ Technologies", emails: ["careers@atliq.com", "info@atliq.com", "sales@atliq.com"] },
  { name: "Spraxa Solutions", emails: ["careers@spraxa.com"] },
  { name: "Appnox Technologies", emails: ["hirings@appnox.ai", "sales@appnox.ai"] },
  { name: "Startappss System", emails: ["hr@startappss.com"] },
  { name: "Tectura Infotech", emails: ["IN.careers@tectura.com", "info@tectura.com", "in.information@tectura.com"] },
  { name: "Intone Networks", emails: ["info@intone.com"] },
  { name: "INVIA", emails: ["hr@invia.co.in", "sales@invia.com.au"] },
  { name: "CloudBoson Technologies", emails: ["support@cloudboson.com"] },
  { name: "Fusionnet", emails: ["info@fusionnet.in", "support@fusionnet.in"] },
  { name: "Gemalto / Thales", emails: ["technical.support@gemalto.com"] },
  { name: "Intellismith Services", emails: ["info@intellismith.com"] },
  { name: "InfoAxon Technologies", emails: ["contactus@infoaxon.com"] },
  { name: "KMG Infotech / KMG", emails: [] },
  { name: "Logix Infosecurity", emails: ["sales@logix.in", "mkt@logix.in"] },
  { name: "Rams Creative Technologies", emails: ["info@ramscreative.com", "support@ramscreative.com"] },
  { name: "Invince / UpsideLMS", emails: ["contact@invince.com"] },
  { name: "Infinity, a Stamford Technology Company", emails: ["info@infinitysts.com"] },
  { name: "Daphnis Software Services", emails: [] },
  { name: "Adore Technosoft", emails: ["hiring@adoretechnosoft.com", "hr@adoretechnosoft.com", "info@adoretechnosoft.com", "sales@adoretechnosoft.com"] },
  { name: "Speqto Technologies", emails: ["career@speqto.com", "info@speqto.com"] },
  { name: "Zebra Technologies", emails: [] },
  { name: "FloBiz", emails: ["hr@flobiz.in", "nitin@flobiz.in", "support@flobiz.in"] },
  { name: "Sellcraft Global Solutions", emails: ["info@sellcraft.net", "karishma@sellcraft.net", "anupama@sellcraft.net"] },
  { name: "ROI NET Solution", emails: ["hr@roinet.in", "contact@roinet.in"] },
  { name: "StrategicERP", emails: ["enquiry@strategicerp.com"] },
  { name: "webdew", emails: ["hr@webdew.com", "sales@webdew.com"] },
  { name: "DCM Infotech", emails: ["shivam.dwivedi@dcminfotech.com", "sales@dcminfotech.com", "secretarial@dcminfotech.com"] },
  { name: "Airpay Payment Services", emails: ["customerservice@airpay.co.in", "customercare@airpay.co.in", "cards@airpay.co.in"] },
  { name: "BANGMETRIC", emails: ["connect@bangmetric.com"] },
  { name: "Vehant Technologies", emails: ["contact@vehant.com"] },
  { name: "Hestabit Technologies", emails: ["friends@hestabit.com", "query@hestabit.com"] },
  { name: "Optimus Information", emails: ["info@optimusinfo.com", "sales@optimusinfo.com"] },
  { name: "MRI Software", emails: ["prakruti.sharma@mrisoftware.com"] },
  { name: "Creativelipi Webtech", emails: ["hr@creativelipi.com", "mail@creativelipi.com"] },
  { name: "Nxtra Data", emails: ["business@nxtra.in"] },
  { name: "Xcelore", emails: ["sales@xcelore.com"] },
  { name: "Lotus Wireless Technologies", emails: ["hr@lotuswireless.com", "info@lotuswireless.com"] },
  { name: "STPL", emails: ["info@stpl.biz"] },
  { name: "BCITS", emails: ["hr@bcits.co.in", "sales@bcits.co.in", "info@bcits.co.in"] },
  { name: "Continuum Managed Services", emails: [] },
  { name: "KritiKal Solutions", emails: ["career@kritikalvision.ai", "sales@kritikalsolutions.com"] },
  { name: "Clixlogix Technologies", emails: ["career@clixlogix.com", "hr@clixlogix.com", "info@clixlogix.com"] },
  { name: "Konverge Technologies", emails: ["hr.gurgaon@konverge.co.in", "hr.mumbai@konverge.co.in"] },
  { name: "PhiStream Consulting", emails: ["info@phistream.com"] },
  { name: "Dhatsol IT Solutions", emails: ["hr@dhatsol.com"] },
  { name: "Meon Technologies", emails: ["hr@meon.co.in"] },
  { name: "Bourntec Solutions", emails: ["ram@bourntec.com"] },
  { name: "Nspire Automation", emails: ["arvind.agarwal@progressive.in"] },
  { name: "Niveshan Technologies India", emails: ["careers@ntplindia.in", "info@ntplindia.in"] },
  { name: "Paytail", emails: ["support@paytail.com", "grievance.officer@paytail.com"] },
  { name: "Saxon Global", emails: ["info@saxonglobal.com"] },
  { name: "Mobulous Technologies", emails: ["info@mobulous.com", "sales@mobulous.com"] },
  { name: "Rang Technologies", emails: ["info@rangtech.com", "sales@rangtech.com"] },
  { name: "Krazy Mantra IT", emails: ["jobs@krazymantra.com", "careers@krazymantra.com", "career@krazymantra.com"] },
  { name: "Cryptograph Technologies", emails: ["info@cryptographtech.com"] },
  { name: "Softmason Technologies India", emails: ["info@softmason.com"] },
  { name: "Codeflies Technologies", emails: ["hr@codeflies.com", "info@codeflies.com", "sales@codeflies.com"] },
  { name: "ACS Technologies", emails: ["neelam@acstechnologies.net", "info@acstechnologies.net"] },
  { name: "JellyFish Technologies", emails: ["hr@jellyfishtechnologies.com", "enquiry@jellyfishtechnologies.com"] },
  { name: "Modus Information Systems", emails: [] },
  { name: "Keen & Able Computers", emails: ["sales@keenable.in"] },
  { name: "Icon Resources & Technologies", emails: ["delhi@iconresources.com", "bangalore@iconresources.com", "mumbai@iconresources.com"] },
  { name: "Primus Software Corporation", emails: ["sales@primussoft.com"] },
  { name: "9Yards Technology", emails: ["sales@9yardstechnology.com"] },
  { name: "A S Software Services", emails: ["hr@a3spl.com"] },
  { name: "General Technologies", emails: ["recruiter@generaltechnologies.co.in", "connect@generaltechnologies.co.in"] },
  { name: "Ameri100 / TSP", emails: ["info@tsp.tech"] },
  { name: "Cloudare Technologies", emails: ["hello@cloudare.in"] },
  { name: "AdPushup", emails: [] },
  { name: "ThunderSoft", emails: ["biz_india@thundersoft.com"] },
  { name: "Nile Technologies", emails: ["prerana.verma@niletechnologies.com", "enquiry@niletechnologies.com"] },
  { name: "Williams Commerce", emails: ["hr@williamscommerce.com", "sales@williamscommerce.com"] },
  { name: "MetaDesign Solutions", emails: ["hr@metadesignsolutions.com", "sales@metadesignsolutions.com"] },
  { name: "InfoStride", emails: ["reachus@infostride.com", "govt@infostride.com"] },
  { name: "AHOM Technologies", emails: ["hr@ahomtech.com"] },
  { name: "Flexis IT", emails: [] },
  { name: "ONE Business Consulting Group", emails: ["careers.in@onebcg.com"] },
  { name: "Singsys Pte", emails: ["info@singsys.com"] },
  { name: "CEBS Worldwide", emails: [] },
  { name: "Paxcom India", emails: ["careers@paxcom.ai", "info@paxcom.ai"] },
  { name: "Inventive Software Solutions", emails: ["bd@isspl.co.in", "appointment@isspl.co.in"] },
  { name: "Cs Soft Solutions", emails: ["careers@cssoftsolutions.com", "info@cssoftsolutions.com"] },
  { name: "Droom Technology", emails: ["careers@droom.in"] },
  { name: "AppSierra Solutions", emails: ["hr@appsierra.com", "info@appsierra.com"] },
  { name: "Packet Shaper Technologies", emails: ["contact@packets.com"] },
  { name: "JSG Innotech", emails: ["info@jsginnotech.com", "career@jsginnotech.com"] },
  { name: "Fiserv India", emails: [] },
  { name: "NIIT Technologies / Coforge", emails: [] },
  { name: "Trantor", emails: ["careers@trantorinc.com", "info@trantorinc.com"] },
  { name: "Axtria India", emails: ["careers@axtria.com"] },
  { name: "CPA Global / Clarivate", emails: [] },
  { name: "Viithiisys Technologies", emails: ["contact@viithiisys.com", "hr@viithiisys.com"] },
  { name: "Innodata Isogen", emails: ["recruitment@innodata.com", "sales@innodata.com"] },
  { name: "Supplified Technologies", emails: ["info@supplified.com"] },
  { name: "Appentus Technologies", emails: ["hr@appentus.com", "info@appentus.com", "sales@appentus.com"] },
  { name: "Enthralltech", emails: ["hr@enthralltech.com", "info@enthralltech.com"] },
  { name: "Zettaone Technologies India", emails: ["contact@zettaone.com", "sales@zettaone.com"] },
  { name: "Moptra Infotech", emails: ["info@moptra.com", "careers@moptra.com"] },
  { name: "Avya Technology", emails: ["contact@avya.co.in", "hr@avya.co.in"] },
  { name: "Delphin Technologies", emails: [] },
  { name: "HL Technologies", emails: ["info@hltechnologies.in"] },
  { name: "Vxceed Software Solutions", emails: ["contactus@vxceed.com"] },
  { name: "Bloom Consulting Services", emails: ["contact@bloomcs.com"] },
  { name: "Xeenius Technology", emails: ["info@xeenius.com"] },
  { name: "Medocity India", emails: ["careers@medocity.com"] },
  { name: "Netcom Softech", emails: ["info@netcomsoftech.com", "career@netcomsoftech.com"] },
  { name: "Central Data Systems", emails: ["info@cds-india.com"] },
  { name: "IndiaNIC", emails: ["hr@indianic.com", "sales@indianic.com"] },
  { name: "Rigel Networks", emails: ["careers@rigelnetworks.com", "sales@rigelnetworks.com"] },
  { name: "Crest Infosystems", emails: ["careers@crestinfosystems.com", "sales@crestinfosystems.com"] },
  { name: "Alobha Technologies", emails: ["hr@alobhatechnologies.com", "info@alobhatechnologies.com"] },
  { name: "Incaendo Technologies", emails: ["info@incaendo.com"] },
  { name: "Techugo", emails: ["hr@techugo.com", "info@techugo.com"] },
  { name: "TechnoScore", emails: ["info@technoscore.com", "hr@technoscore.com"] },
  { name: "FCS Software Solutions", emails: ["hrd@fcsltd.com", "info@fcsltd.com"] },
  { name: "GirnarSoft / CarDekho Group", emails: ["careers@cardekho.com"] },
  { name: "Cedcoss Technologies", emails: ["jobs@cedcoss.com", "info@cedcoss.com"] },
  { name: "Omninet Technologies", emails: ["info@omninet.biz"] },
  { name: "Mindfire Solutions", emails: ["careers@mindfiresolutions.com"] },
  { name: "Parangat Technologies", emails: ["hr@parangat.com", "sales@parangat.com"] },
  { name: "XenonStack", emails: ["careers@xenonstack.com", "contact@xenonstack.com"] },
  { name: "Bellurbis Technologies", emails: ["hr@bellurbis.com", "info@bellurbis.com"] },
  { name: "Appinventiv Technologies", emails: ["hr@appinventiv.com", "info@appinventiv.com"] },
  { name: "Neuronimbus Software Services", emails: ["careers@neuronimbus.com", "contact@neuronimbus.com"] },
  { name: "TechAhead Software", emails: ["hr@techaheadcorp.com", "sales@techaheadcorp.com"] },
  { name: "Mirketa Software", emails: ["careers@mirketa.com", "contact@mirketa.com"] },
  { name: "Quokka Labs", emails: ["careers@quokkalabs.com", "hello@quokkalabs.com"] },
  { name: "Redian Software", emails: ["info@rediansoftware.com", "careers@rediansoftware.com"] },
  { name: "Dignitas Digital", emails: ["jobs@dignitasdigital.com", "hello@dignitasdigital.com"] },
  { name: "Laitkor Infosolutions", emails: ["careers@laitkor.com", "info@laitkor.com"] },
  { name: "Digital Avenues", emails: ["jobs@digitalavenues.com"] },
  { name: "Audax Labs", emails: ["careers@audaxlabs.com", "contact@audaxlabs.com"] },
  { name: "Filix Consulting", emails: ["info@filixconsulting.com"] },
  { name: "Savantis Solutions India", emails: ["info@savantis.com", "careers@savantis.com"] },
];

// Filter to only new companies (not already in tracker)
const newCompanies = [];
let nextId = maxId + 1;

for (const entry of ambitionCompanies) {
  const n = norm(entry.name);
  if (existingNorms.has(n)) {
    console.log(`Skipping (already in tracker): ${entry.name}`);
    continue;
  }
  
  // Also check research file for any additional emails
  const researchEntry = researchMap[n];
  const allEmails = [...new Set([
    ...(entry.emails || []),
    ...(researchEntry?.emails || []),
  ])];
  
  newCompanies.push({
    id: nextId++,
    companyNumber: nextId - 1,
    companyName: entry.name,
    roleTarget: "",
    location: "",
    companySize: "Unknown",
    website: "",
    linkedin: "",
    basicInfo: `Target role: Unknown. Preferred location: Unknown.`,
    appliedDate: "",
    status: "Pending",
    emails: allEmails,
    notes: "",
  });
}

console.log(`\nNew companies to add: ${newCompanies.length}`);
console.log(`ID range: ${maxId + 1} - ${nextId - 1}`);

// Append to overrides
overrides.push(...newCompanies);
writeFileSync(overridesPath, JSON.stringify(overrides, null, 2) + "\n");
console.log("Appended to trackerOverrides.json ✓");
